# Exporting Component Description of RTG4_SRAM_AHBL_AXI_C0 to TCL
# Family: RTG4
# Part Number: RT4G150_ES-CG1657
# Create and Configure the core component RTG4_SRAM_AHBL_AXI_C0
create_and_configure_core -core_vlnv {Actel:SystemBuilder:RTG4_SRAM_AHBL_AXI:1.0.123} -component_name {RTG4_SRAM_AHBL_AXI_C0} -params {\
"AHBL_TIMEOUT_COUNT:80" \
"AXI4_AWIDTH:32" \
"AXI4_DWIDTH:64" \
"AXI4_IDWIDTH:8" \
"AXI4_IFTYPE_RD:T" \
"AXI4_IFTYPE_WR:T" \
"AXI4_WRAP_SUPPORT:F" \
"AXI_READ_TIMEOUT_COUNT:80" \
"AXI_WRITE_TIMEOUT_COUNT:80" \
"BYTEENABLES:1" \
"BYTE_ENABLE_WIDTH:8" \
"B_REN_POLARITY:2" \
"CASCADE:1" \
"ECC_OPTIONS:0" \
"FABRIC_INTERFACE_TYPE:1" \
"HI_REL:F" \
"IMPORT_FILE:" \
"INIT_RAM:F" \
"LPM_HINT:0" \
"PIPELINE_OPTIONS:1" \
"RDEPTH:1024" \
"RESET_TYPE:ASYNCHRONOUS" \
"RWIDTH:72" \
"USE_NATIVE_INTERFACE:F" \
"WDEPTH:1024" \
"WWIDTH:72" }
# Exporting Component Description of RTG4_SRAM_AHBL_AXI_C0 to TCL done
